name: baki_clock
description: Baki clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  provider: ^4.0.1
  cupertino_icons: ^0.1.2
  states_rebuilder: ^1.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:        
    - family: IBMPlexSans-Medium
      fonts:
        - asset: third_party/IBMPlexSans-Medium.ttf                      
    - family: BebasNeue-Regular
      fonts:
        - asset: third_party/BebasNeue-Regular.ttf                                               
  assets:
    - assets/elements/droid_open_mouth_left.png
    - assets/elements/droid_open_mouth_right.png
    - assets/elements/droid_idle.png
    - assets/elements/apple_bitten.png
    - assets/elements/apple.png
    - assets/elements/
    - assets/elements/ghosts/
    - assets/weather/dark/
    - assets/weather/light/  

